# Generated by Django 5.0.1 on 2024-01-31 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=50)),
                ('employeeRole', models.CharField(choices=[('e', 'General Employee'), ('m', 'Manager'), ('h', 'Human Resource')], default='e', max_length=1)),
            ],
            options={
                'ordering': ['employeeId'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('projectTitle', models.CharField(max_length=100)),
                ('dateOfStart', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-dateOfStart'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leaveId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('employeeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Employee.employeeinfo')),
            ],
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='projectId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Employee.project'),
        ),
    ]
