# Generated by Django 5.0.1 on 2024-01-31 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_employeeinfo_managerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='managerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Employee.employeeinfo'),
        ),
    ]
